version: "3.8"

services:
  java:
    container_name: java_app
    image: maven:3.9.1-eclipse-temurin-17
    working_dir: /app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver
    depends_on:
      - postgres
    volumes:
      - ./src:/app/src
      - ./pom.xml:/app/pom.xml
      - /app/target
    command: mvn spring-boot:run

  postgres:
    container_name: postgres
    image: "postgres:latest"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
