version: "3.8"

services:
  react-app:
    container_name: react-app
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/tv-show-reminder-app:/react-app
      - /react-app/node_modules
    stdin_open: true
    tty: true
    environment:
      - NODE_ENV=development

  java:
    container_name: java_app
    image: maven:3.9.1-eclipse-temurin-17
    working_dir: /java-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
    depends_on:
      - postgres
    volumes:
      - ./backend/src:/java-app/src
      - ./backend/pom.xml:/java-app/pom.xml
      - ./backend/target:/java-app/target
    command: mvn spring-boot:run

  postgres:
    container_name: postgres
    image: "postgres:latest"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
